name: Call a reusable workflow

on:
    push:
      branches: [development]
    pull_request:
      branches: [development]
jobs:
  eslint:
    uses: Globy-Solutions/workflows-actions/master/eslint.yml@main

  prettier:
    uses: Globy-Solutions/workflows-actions/master/prettier.yml@main

  jest:
    uses: Globy-Solutions/workflows-actions/master/jest.yml@main
